const SYSTEM_INSTRUCTION = `You are NIVA, the BPSC Intelligence Companion inside BPSC Nexus. You are an expert mentor for Indian competitive exams, especially BPSC Prelims and Mains. Be accurate, structured and exam-oriented. When a question is supplied, explain the correct answer first and why distractors are wrong when useful. Never expose internal answer indexes. Preserve supplied question/source explanation and distinguish your analysis. For Mains, emphasize analytical structure, dimensions, examples, constitutional/legal basis and answer-writing value. For Prelims, emphasize factual anchors, elimination clues and traps. Do not fabricate current affairs, statistics, schemes, dates or constitutional provisions. Keep responses useful on mobile. Output clean plain text only.`;
const TRANSLATION_INSTRUCTION = `You are the official bilingual translation engine for a BPSC preparation application. Translate English segments into precise exam-standard Hindi. Preserve every factual detail, number, date, Article number, option marker, acronym, proper noun, scheme name and technical term. Do not summarize, omit, expand, reorder, explain or correct the source. Return exactly one Hindi string for every input segment in the same order.`;
const model = process.env.GEMINI_MODEL || 'gemini-3.8-flash';
function extractOutput(interaction){if(typeof interaction?.output_text==='string'&&interaction.output_text.trim())return interaction.output_text.trim();const texts=[];for(const step of interaction?.steps||[]){if(step?.type!=='model_output')continue;for(const block of step?.content||[]){if(block?.type==='text'&&block.text)texts.push(block.text)}}return texts.join('\n').trim()}
async function gemini(body, instruction){
  if(!process.env.GEMINI_API_KEY) throw new Error('GEMINI_API_KEY is not configured.');
  const r=await fetch('https://generativelanguage.googleapis.com/v1beta/interactions',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':process.env.GEMINI_API_KEY},body:JSON.stringify({model,system_instruction:instruction,input:body,store:false})});
  const d=await r.json().catch(()=>({})); if(!r.ok)throw new Error(d?.error?.message||`Gemini HTTP ${r.status}`); const t=extractOutput(d); if(!t)throw new Error('Gemini returned no text.'); return t;
}
export function attachNivaRoutes(app){
  app.post('/api/niva',async(req,res)=>{try{const p=req.body||{};if(!String(p.message||'').trim())return res.status(400).json({error:'Message is required.'});const history=Array.isArray(p.history)?p.history.slice(-12):[];const context=JSON.stringify(p.context||{}).slice(0,18000);const transcript=history.map(x=>`${x?.role==='assistant'?'NIVA':'Student'}: ${String(x?.text||'').slice(0,3500)}`).join('\n');const input=`BPSC APP CONTEXT:\n${context}\n\nRECENT CONVERSATION:\n${transcript}\n\nCURRENT STUDENT MESSAGE:\n${String(p.message).slice(0,9000)}`;res.json({text:await gemini(input,SYSTEM_INSTRUCTION),model});}catch(e){res.status(500).json({error:e.message||'NIVA backend error.'})}});
  app.post('/api/translate',async(req,res)=>{try{const p=req.body||{};const seg=Array.isArray(p.segments)?p.segments.map(x=>String(x??'').slice(0,1800)):[];if(!seg.length||seg.length>30)throw new Error('Translation batch must contain 1–30 segments.');const input=`Translate these segments to Hindi. Return a JSON array with exactly ${seg.length} strings.\n${JSON.stringify(seg)}`;const raw=await gemini(input,TRANSLATION_INSTRUCTION);let parsed;try{parsed=JSON.parse(raw)}catch{const m=raw.match(/\[[\s\S]*\]/);if(!m)throw new Error('Invalid translation output.');parsed=JSON.parse(m[0])}if(!Array.isArray(parsed)||parsed.length!==seg.length)throw new Error('Invalid translation segment count.');res.json({translations:parsed,model});}catch(e){res.status(500).json({error:e.message||'Translation backend error.'})}});
}
